### ISSUE TITLE
When launching mbed-client-linux-example for the first time it should ask for credentials

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-client-linux-example#26]
Currently you need to specify your server config in a header file, but there is no notion of this when you start up the example. It'll just yield `Error occured  : M2MInterface::NetworkError`.

If there's no data provided in the header we should either throw an error that indicates that, but it would be even better to just ask the user for it's credentials via stdin (or do it via a link like we do with yotta).

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-529

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
