### ISSUE TITLE
The example is not cleaning up correctly when terminated with ctrl-c

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux-example#31]
When the program is terminated with ctrl-c, exit() is called in ctrl_c_handle_function(), which means the main() function never gets to run the clean-up code (e.g. pthread_join(), pthread_detach(), ~MbedClient() etc.) to properly release resources.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-592

**Comment by yogpan01** [comment]
Hi, this should be now fixed . Please check the latest sources for the example.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
