### ISSUE TITLE
mbed-client-linux-example with mbed-cli

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-linux-example#46]
Is there a plan to move this repo to mbed-cli?

Would there be a linux-native target in mbed-os? Or how would this be integrated?

FYI @devran01

**Comment by yogpan01** [comment]
Hi Markus,
Currently there are no plans to make any changes to non mbed OS mbed Client project.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
