### ISSUE TITLE
Out-of-order notifications seen on reconnections (if at all)

### ISSUE THREAD

**Issue by vanti** [ARMmbed/mbed-client-linux-example#47]
I am running the mbed-client-linux-example on a ubuntu PC, and a script that subscribes to the '/Test/0/D' resource using the python connector api on a different PC. The example runs fine and the script is able to display the resource value as monotonically increasing. However, if I disconnect my ubuntu PC from the network for a few seconds using the toggle on the top right hand corner of the desktop, e.g. right when /Test/0/D is set to 2, and then reconnect it to the network when it is set to 6, I see the notifications come in out-of-order in the script as a sudden 'burst':

2
4
6
5
3
7

This means a device that loses network connection temporarily would result in notifications being received in a random order. It'd be nice to ensure notifications are sent and received in order during reconnections.

I am using mbed-client version 1.13.4. Also this behavior is seen in TCP mode. In UDP mode, notifications are no longer received at all in the script after the reconnection.

**Comment by yogpan01** [comment]
mbed Client doesnt store notifications so its very likely the notifications are missed or re-ordered. In TCP mode , most probably its the underlying TCP stack buffer which might be holding on the values which is then received on reconnection. In UDP mode this is not the case so notifications are lost.
One more question, on your script are you having these notifications received as notifications ? If yes, is the resource pre-subscribed to receive notifications ? Because when there is reconnection logic, client does complete registration, that means the notifications will get a new subscriber token and start sending notifications using new token. That might be the issue, can you please check using wireshark if the notifications are still going through after re-connection of client.

**Comment by vanti** [comment]
Thanks for looking into this. I am using the putResourceSubscription() API in the python connector. Using pre-subscription (ie. putPreSubscription()) does not seem to help. However, in UDP mode the script can receive notifications again after it re-subscribes to the same resource by calling putResourceSubscription() in the script post-reconnection. This is not ideal, since the script typically does not know when a reconnection occurred, so it would have to call putResourceSubscription() every time it receives a 'register update' message.

In Wireshark I do not see the notifications being sent anymore after observing the DTLS handshake that was the result of a reconnection, til the script re-subscribes.

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
