### ISSUE TITLE
how to invoke incoming_block_message_callback?

### ISSUE THREAD

**Issue by fwndz** [ARMmbed/mbed-client-linux-example#53]
hi,

I have question related to the given example. How can I invoke the incoming_block_message_callback and outgoing_block_message_callback from the example? Is there any platform should I used. I tried with mbed api dashboard but it did not work. Can I implement it by using curl, httpie or postman?
if yes how can I do it.

Cheers

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
