### ISSUE TITLE
Is there a mirror which is not in private repo?

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/mbed-client-linux-example#55]
I thought we had one but can't find it?

**Comment by teetak01** [comment]
Closing the issue as inactive and due to the repository being deprecated.

Please take a look at our current offering at https://cloud.mbed.com/docs/current. The actively maintained version of this component can be found in http://github.com/armmbed/mbed-cloud-client.

Please open a new issue if this is still valid. We strongly encourage you to migrate to the latest product. New issues in this repository will most likely remain unfixed.
